# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

data=pd.read_csv('/content/Iris.csv')
data.head()

data.filter(["Id","Species", "SepalLengthCm", "SepalLengthCm"]).head()

data.isnull().sum()

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='SepalLengthCm', y='SepalWidthCm', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_0['Id'].plot(kind='hist', bins=20, title='Id')
plt.gca().spines[['top', 'right',]].set_visible(False)

plt.bar(data['Species'], data['SepalLengthCm'])
plt.title("Iris Dataset")
plt.xlabel("Species")
plt.ylabel("SepalLengthCm")
plt.show()

x = data.drop(columns="Species")
y = data["Species"]
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

x.head()

y.head()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4, random_state = 1)

x_train.head()

x_test.head()

y_train.head()

y_test.head()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score

from sklearn.linear_model import LogisticRegression
log_model= LogisticRegression(random_state = 1)
log_model.fit(x_train, y_train)

y_test_pred = model.predict(x_test)
y_train_pred = model.predict(x_train)

print("Accuracy of Training : ", accuracy_score(y_train, y_train_pred)*100)
print("Accuracy of Test: ", accuracy_score(y_test, y_test_pred)*100)

